### PR TITLE
DE27079: DnD performance fix.

### PR DESCRIPTION
**Pull request by limscoder**
Fixes memory leak and optimizes drop target hit detection. Enables nested drop targets.

Memory was leaking for 2 reasons:

1. `_rootNodeID` check was not valid so drop targets were getting duplicated within `_dropTargets` every time they were re-rendered.
2. Unmounted components weren't being properly removed from `_dropTargets` array.

I introduced a backend callback `unmountDragDropComponent` that the mixin calls so unmounted drop targets will get cleaned-up properly. This breaks compatibility with react-dnd, but we're so far behind it doesn't really matter, since we have to do 2 major version upgrades to get to master anyway.

Having fewer drop target elements to loop through helped hit detection, but I also changed the hit detection method to avoid calling `getBoundingClientRect`, since that causes a reflow.

DnD performance seems to be significantly improved both via profiling and via perceived performance.

Nested drop targets are enabled by taking the inner-most matching drop target.

### CODE REVIEW

**Comment by pbomb** [comment]
LGTM

**Comment by esoman** [comment]
This is great!  One question, does this still work with drop targets in drop targets and the new and greatly improved `findDropTarget`

**Comment by esoman** [comment]
I thought they had nested drop targets on Team Plan?  Let me check.

**Comment by esoman** [comment]
@limscoder, never mind, that was something kumquats wanted for team plan and something we were considering when we were looking for a react-dnd replacement.  It is currently not supported by our version and not on the team plan page.

**Pull request merged**
